### ISSUE TITLE
Create uuid for all automations

### ISSUE THREAD

**Issue by pinkywafer** [pinkywafer/Home-Assistant_Config#14]
good reasons here:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Yes, I give all manually made automations a unique ID by setting a UUID (<a href="https://t.co/1lakXw3OI9">https://t.co/1lakXw3OI9</a>).<br><br>This enables frontend features like: Setting name/icon/entity ID, and allows the UI to show relations between automations and entities/devices/area.</p>&mdash; Franck Nijhof (@Frenck) <a href="https://twitter.com/Frenck/status/1284871918089383936?ref_src=twsrc%5Etfw">July 19, 2020</a></blockquote>

**Comment by CCOSTAN** [comment]
Did you script this somehow or just do it by hand?

**Comment by pinkywafer** [comment]
did by hand, but used the uuid generator for vscode
