### ISSUE TITLE
Set up discord channel for home assistant instance

### ISSUE THREAD

**Issue by pinkywafer** [pinkywafer/Home-Assistant_Config#22]
For various notifications

**Comment by CCOSTAN** [comment]
No Slack? :)

**Comment by pinkywafer** [comment]
> No Slack? :)

Strangely... I don't have slack!

**Comment by pinkywafer** [comment]
Channel created on my (currently otherwise empty!) server.

If anyone wants to join , the link is:
https://discord.gg/UcWVaJP

feel free to suggest any channels in the general channel

**Comment by pinkywafer** [comment]
use this for notifications for #18

**Comment by pinkywafer** [comment]
in progress - follow #18
