### ISSUE TITLE
Automation for update spamming github update issue

### ISSUE THREAD

**Issue by pinkywafer** [pinkywafer/Home-Assistant_Config#23]
Add a check to prevent spamming the github issue

**Comment by pinkywafer** [comment]
The repeated messages are occurring when home assistant is restarted... (Ie when I'm meddling with things!). Add check and do not notify github issue if already notified

**Comment by pinkywafer** [comment]
My preferred way of achieving this is to use an input text as a variable which can be set to the version notified.
The automation was running at home assistant start to allow the persistant notification to be restored - this can be achieved by #24

**Comment by jcallaghan** [comment]
I use a rest_command to look for an issue with a certain title in my GitHub issues. If one is found then I don't create a new issue. https://github.com/jcallaghan/home-assistant-config/issues/105#issuecomment-645047409

**Comment by pinkywafer** [comment]
@jcallaghan i had thought of going that route, to start with, but really, the only reason i wanted the automation (and several others) to run at start was to restore the persistent notification, so adding the mqtt notification save + restore has solved that issue for all. 
It would be possible to go down the same route, but I'd have to search issue comments, as I'm using one issue as an update tracker which home Assistant reopens, comments version available and then comments Travis build status also.
I did also debate having an automation to simply close the issue again, then debated an automation to stage, commit and push the updated `.HA_VERSION` file and close the issue, but so far I'm undecided as to whether i want to implement it!

**Comment by jcallaghan** [comment]
This is why I love Home Assistant and see repos like yours and Carlo's as there is no one right way and we learn and get inspiration from one another. I've not built out anything with Travis yet but it is on the cards. I need to finish moving my code from my private repo first.
