### ISSUE TITLE
Migrate off travis-ci

### ISSUE THREAD

**Issue by pinkywafer** [pinkywafer/Home-Assistant_Config#43]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

New pricing structure being implemented. The free tier apparently does not ever renew, so seems like a one time gig. This would mean a subscription of a minimum of $69 a month!!! 
If this is the case, GitHub actions may be the only option

**Comment by BeardedTinker** [comment]
Nice catch! Missed it completely.
It's good then that I've already done GitHub workflow/actions.
Migrating is really easy, you can check here my config:
https://github.com/BeardedTinker/Home-Assistant_Config/tree/master/.github

**Comment by pinkywafer** [comment]
@BeardedTinker thanks!  I was also looking at @frenck who has done the same thing.
Now need to work out how to get that information into Home Assistant - looks like I'll have to consult the GitHub API again!

**Comment by pinkywafer** [comment]
I now have github actions set up to do 7 checks!! - yamllint, remarklint, esphome checks, and check home assistant config against currently installed version, latest, beta and dev (although I have dev set to pass on failure at the moment - I have really only included this for my reference, and I can look at the build to see if there are any upcoming issues - I'm not running dev, and any changes which break during development would affect the overall check suite otherwise)

**Comment by pinkywafer** [comment]
To get this into home assistant, I have decided to use github webhooks so as to avoid any issues with api rate limiting.
I have a webhook set up especially for this which sends the webhook to my home assistant instance triggered on check_runs.  I'm sure this could be done using check_suite, but using check_run allows me to get the status of all 7 check run jobs into home assistant.
I'm then using the webhook automation to publish a retained mqtt message with the relevant parts of the webhook payload and then have 7 manually configured mqtt sensors to read the data from the mqtt message

**Comment by pinkywafer** [comment]
still to do:
 * [x] trigger github check run from homeassistant in home assistant update available automation
 * [x] check the github_actions_homeassistant_latest in the update automation
 * [x] add github actions sensors to frontend

**Comment by pinkywafer** [comment]
going to leave this as it is for now and see how it goes.
Next step will then be to remove travis

**Comment by pinkywafer** [comment]
The github actions are running nicely.  Time to remove Travis-ci

**Comment by pinkywafer** [comment]
Travis app uninstalled from Github...
